[package]
name = "lfqueue"
version = "0.1.0"
edition = "2024"


[target.'cfg(loom)'.dependencies]
loom = "0.7.2"

[dependencies]
crossbeam-utils = "0.8.21"
lockfree = "0.5.1"
owned-alloc = "0.2.0"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "syncqueue"
harness = false
